name: Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Remove unnecessary files from deployment
      - name: Remove unnecessary files
        run: |
          rm -r .git
          rm -r .github
          rm .gitignore README.md
          
      # Setting up path.js - changing path variable
      - name: Setting up path.js
        run: |
            rm -f path.js
            touch path.js
            echo "export const path = '/root/opulanceBackend';
                  export const sliceCommandHead = 'prusa-slicer'; 
                  export const sliceCommandTail = '';
            " >> path.js
            cat path.js

      # https://github.com/marketplace/actions/copy-via-ssh
      - name: Copy content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./
          remote: /root/opulanceBackend
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          tryKeyboard: false
          rmRemote: true
          concurrency: 5
          
      # Install dependencies and start server
      - name: Installing dependencies and starting server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: | 
            cd opulanceBackend
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install
            pm2 start index.js
